// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_login_screen', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_email', async function() {
    {
      const element = await driver.findElement(By.id(":r9:"))
      assert(await element.isEnabled())
    }
  })
  it('test_password_editable', async function() {
    {
      const element = await driver.findElement(By.id(":rb:"))
      assert(await element.isEnabled())
    }
  })
  it('test_password_present', async function() {
    {
      const elements = await driver.findElements(By.id(":rb:"))
      assert(elements.length)
    }
  })
  it('test_username_present', async function() {
    {
      const elements = await driver.findElements(By.id(":r9:"))
      assert(elements.length)
    }
  })
})
