// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_user_homepage', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_userhome_pfp', async function() {
    {
      const elements = await driver.findElements(By.css(".css-1sb2j9v > .css-13gzsmf > img"))
      assert(elements.length)
    }
  })
  it('test_userhome_post', async function() {
    {
      const element = await driver.findElement(By.css(".MuiInputBase-input"))
      assert(await element.isEnabled())
    }
  })
  it('test_userhome_socials', async function() {
    {
      const elements = await driver.findElements(By.css(".css-1j1nv1o img"))
      assert(elements.length)
    }
  })
  it('test_userhome_stats', async function() {
    {
      const elements = await driver.findElements(By.css(".css-y24341 > .css-1o8dqds-MuiTypography-root"))
      assert(elements.length)
    }
  })
  it('test_username_present', async function() {
    {
      const elements = await driver.findElements(By.id(":r9:"))
      assert(elements.length)
    }
  })
})
