// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_new_user', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_add_email', async function() {
    {
      const element = await driver.findElement(By.id(":r9:"))
      assert(await element.isEnabled())
    }
  })
  it('test_add_lastname', async function() {
    {
      const element = await driver.findElement(By.id(":rn:"))
      assert(await element.isEnabled())
    }
  })
  it('test_add_picture', async function() {
    {
      const elements = await driver.findElements(By.css(".css-1025vi4 > p"))
      assert(elements.length)
    }
  })
  it('test_add_username', async function() {
    {
      const element = await driver.findElement(By.id(":rl:"))
      assert(await element.isEnabled())
    }
  })
  it('test_button', async function() {
    {
      const elements = await driver.findElements(By.css(".MuiButtonBase-root"))
      assert(elements.length)
    }
  })
  it('test_location', async function() {
    {
      const element = await driver.findElement(By.id(":rp:"))
      assert(await element.isEnabled())
    }
  })
})
